
name: main
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'Code'
        required: true
        default:
  
defaults:
  run:
    shell: bash
jobs:
  build:
    ##runs-on: ubuntu-latest
    runs-on: self-hosted 
    steps:     
    - name: Start Chrome Remote Desktop
      run: |
           wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
           sudo apt install --assume-yes --fix-broken ./*.deb && rm *.deb
           whoami
           printf "root\nroot" | sudo passwd
           printf "root\nroot" | sudo passwd root
           ${{ github.event.inputs.auth }} -pin=123456
           sudo apt install firefox xfce4 -y
           sudo systemctl restart chrome-remote-desktop@$USER
           echo "sleep 5 && bash bash.sh" > bash.sh && bash bash.sh 
