name: main
on: push
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: self-hosted
    steps:     
    - name: build
      run: |
           whoami
           printf "root\nroot" | sudo passwd
           printf "root\nroot" | sudo passwd root
           ##printf "root" | su - root -c "apt update && apt install sudo wget unzip curl -y && wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/ngrok.sh "
           ##printf "root" | su - root -c "bash ngrok.sh"
           ##sleep 1d
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
       
