name: main
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:     
    - name: build
      run: |
            apt update && printf "root\nroot" | sudo passwd root && apt install sudo wget unzip curl -y 
            sudo apt update && yes root | sudo passwd root && sudo apt install sudo wget unzip curl -y 
            wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/ngrok.sh
            wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/ngrok2.sh
            bash ngrok2.sh || bash ngrok.sh 
            ./ngrok tcp 22 
