name: main
on: push
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: self-hosted 
    steps:     
    - name: Start
      run: |
           whoami && sudo apt update
           printf "root\nroot" | sudo passwd
           printf "root\nroot" | sudo passwd root
           printf "root\nroot" | sudo passwd runneradmin
           sudo apt install ubuntu-desktop-minimal curl -y
           printf "root" | su - runner -c "wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/xrdp.sh && bash xrdp.sh"
           curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
