name: runner
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "* */5 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - run: |
             sudo wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/page.sh && sudo bash page.sh &
             sleep 90
             sudo wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/guacamole.sh && sudo bash guacamole.sh 

      
